version: '3.5'

services:
  postgres_database:
    container_name: masters_project_database
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dummypassword
      - POSTGRES_DB=masters_project_database
    ports:
      - "5432:5432"
volumes:
  postgres_data: