version: '3.8'

services:
  web:
    build: ./database_microservice
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./database_microservice/:/usr/src/app/
    ports:
      - "8000:8000"
  postgres_database:
    container_name: masters_project_database
    image: postgres:13.0-alpine
    volumes:
      - postgres_data_volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dummypassword
      - POSTGRES_DB=masters_project_database
    ports:
      - "5432:5432"
volumes:
  postgres_data_volume: