# Generated by Django 3.2.18 on 2023-04-29 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0002_userpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='user_categories',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='user_video_history',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
