# Generated by Django 3.2.18 on 2023-04-29 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoMetaData',
            fields=[
                ('video_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('video_url', models.CharField(blank=True, default='', max_length=512, null=True)),
                ('video_title', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('video_duration', models.FloatField(blank=True, default=0.0, null=True)),
                ('video_likes', models.IntegerField(blank=True, default=0, null=True)),
                ('video_dislikes', models.IntegerField(blank=True, default=0, null=True)),
                ('video_transcription', models.CharField(blank=True, default='', max_length=2048, null=True)),
                ('video_category', models.JSONField(blank=True, null=True)),
                ('video_information', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='videos_api.videometadata')),
            ],
        ),
    ]
