# Generated by Django 3.2.18 on 2023-05-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videometadata',
            name='video_title',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
