# Generated by Django 3.2.18 on 2023-05-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_api', '0002_alter_videometadata_video_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodetails',
            name='vpa_pipeline_status',
            field=models.CharField(blank=True, choices=[('INITIALIZED', 'INITIALIZED'), ('STARTED', 'STARTED'), ('QUEUED', 'QUEUED'), ('COMPLETED', 'COMPLETED'), ('ABORTED', 'ABORTED')], default='INITIALIZED', max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='videodetails',
            name='vpa_video_status',
            field=models.CharField(blank=True, choices=[('QUEUED', 'QUEUED'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED')], default='QUEUED', max_length=36, null=True),
        ),
    ]
