# Generated by Django 3.2.18 on 2023-05-07 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos_api', '0004_auto_20230507_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodetails',
            name='video_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='videos_api.videometadata'),
        ),
    ]
