# Generated by Django 3.2.18 on 2023-05-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_api', '0007_alter_videodetails_video_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
