# Generated by Django 3.2.18 on 2023-05-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_api', '0008_uploadedvideos'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedvideos',
            name='file_url',
            field=models.CharField(blank=True, default='', max_length=2048, null=True),
        ),
    ]
