# Generated by Django 3.2.18 on 2023-05-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos_api', '0009_uploadedvideos_file_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedvideos',
            old_name='file',
            new_name='video_file',
        ),
        migrations.RenameField(
            model_name='uploadedvideos',
            old_name='file_url',
            new_name='video_file_url',
        ),
        migrations.AddField(
            model_name='uploadedvideos',
            name='file_username',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
