# Generated by Django 3.2.18 on 2023-05-08 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos_api', '0010_auto_20230508_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedvideos',
            old_name='file_username',
            new_name='username',
        ),
    ]
